export const AllRegions = [
  {
    state: "Lagos",
    name: "Agbotikuyo",
    lcda: "Agege",
    lat: 6.62,
    long: 3.32,
  },
  {
    state: "Lagos",
    name: "Dopemu",
    lcda: "Agege",
    lat: 6.6167,
    long: 3.3333,
  },
  {
    state: "Lagos",
    name: "Darocha",
    lcda: "Agege",
    lat: 6.621,
    long: 3.325,
  },
  {
    state: "Lagos",
    name: "Iloro",
    lcda: "Agege",
    lat: 6.622,
    long: 3.324,
  },
  {
    state: "Lagos",
    name: "Onipetesi",
    lcda: "Agege",
    lat: 6.618,
    long: 3.329,
  },
  {
    state: "Lagos",
    name: "Isale Odo",
    lcda: "Agege",
    lat: 6.6195,
    long: 3.3265,
  },
  {
    state: "Lagos",
    name: "Isale",
    lcda: "Agege",
    lat: 6.619,
    long: 3.326,
  },
  {
    state: "Lagos",
    name: "Idimangoro",
    lcda: "Agege",
    lat: 6.617,
    long: 3.328,
  },
  {
    state: "Lagos",
    name: "Keke",
    lcda: "Agege",
    lat: 6.623,
    long: 3.323,
  },
  {
    state: "Lagos",
    name: "Okekoto",
    lcda: "Agege",
    lat: 6.624,
    long: 3.322,
  },
  {
    state: "Lagos",
    name: "Oniwaya",
    lcda: "Agege",
    lat: 6.625,
    long: 3.321,
  },
  {
    state: "Lagos",
    name: "Papa-uku",
    lcda: "Agege",
    lat: 6.626,
    long: 3.32,
  },
  {
    state: "Lagos",
    name: "Ori",
    lcda: "Agege",
    lat: 6.627,
    long: 3.319,
  },
  {
    state: "Lagos",
    name: "Orile Agege/oko Oba",
    lcda: "Agege",
    lat: 6.628,
    long: 3.318,
  },
  {
    state: "Lagos",
    name: "Oyewole/papa Ashafa",
    lcda: "Agege",
    lat: 6.629,
    long: 3.317,
  },
  {
    state: "Lagos",
    name: "Ido Aadun",
    lcda: "Agege",
    lat: 6.63,
    long: 3.316,
  },
  {
    state: "Lagos",
    name: "Isale Odan",
    lcda: "Agege",
    lat: 6.631,
    long: 3.315,
  },
  {
    state: "Lagos",
    name: "Ido Gaun",
    lcda: "Agege",
    lat: 6.632,
    long: 3.314,
  },
  {
    state: "Lagos",
    name: "Ipodo",
    lcda: "Agege",
    lat: 6.633,
    long: 3.313,
  },
  {
    state: "Lagos",
    name: "Aaromi",
    lcda: "Agege",
    lat: 6.634,
    long: 3.312,
  },
  {
    state: "Lagos",
    name: "Ido Aagbosu",
    lcda: "Agege",
    lat: 6.635,
    long: 3.311,
  },
  {
    state: "Lagos",
    name: "Magbon",
    lcda: "Agege",
    lat: 6.636,
    long: 3.31,
  },
  {
    state: "Lagos",
    name: "Mulero",
    lcda: "Agege",
    lat: 6.637,
    long: 3.309,
  },
  {
    state: "Lagos",
    name: "Onilekere",
    lcda: "Agege",
    lat: 6.638,
    long: 3.308,
  },
  {
    state: "Lagos",
    name: "Masaku",
    lcda: "Agege",
    lat: 6.639,
    long: 3.307,
  },
  {
    state: "Lagos",
    name: "Ganganja",
    lcda: "Agege",
    lat: 6.64,
    long: 3.306,
  },
  {
    state: "Lagos",
    name: "Ogba",
    lcda: "Agege",
    lat: 6.6267,
    long: 3.3433,
  },
  {
    state: "Lagos",
    name: "Ashade",
    lcda: "Agege",
    lat: 6.6181,
    long: 3.3324,
  },
  {
    state: "Lagos",
    name: "Alausa",
    lcda: "Agege",
    lat: 6.6213,
    long: 3.3615,
  },
  {
    state: "Lagos",
    name: "Agbede",
    lcda: "Agege",
    lat: 6.6254,
    long: 3.32,
  },
  {
    state: "Lagos",
    name: "Adekunle",
    lcda: "Agege",
    lat: 6.623,
    long: 3.328,
  },
  {
    state: "Lagos",
    name: "Operekete",
    lcda: "Agege",
    lat: 6.6285,
    long: 3.319,
  },
  {
    state: "Lagos",
    name: "Akinode",
    lcda: "Agege",
    lat: 6.6302,
    long: 3.3221,
  },
  {
    state: "Lagos",
    name: "Omole",
    lcda: "Agege",
    lat: 6.636,
    long: 3.3422,
  },
  {
    state: "Lagos",
    name: "Aguda",
    lcda: "Agege",
    lat: 6.6289,
    long: 3.3146,
  },
  {
    state: "Lagos",
    name: "Suberu",
    lcda: "Agege",
    lat: 6.6298,
    long: 3.3269,
  },
  {
    state: "Lagos",
    name: "Ajegunle",
    lcda: "Agege",
    lat: 6.6234,
    long: 3.3301,
  },
  {
    state: "Lagos",
    name: "Alayabiagba",
    lcda: "Ajeromi Ifelodun",
    lat: 6.4567,
    long: 3.3314,
  },
  {
    state: "Lagos",
    name: "Aiyetoro",
    lcda: "Ajeromi Ifelodun",
    lat: 6.4602,
    long: 3.3241,
  },
  {
    state: "Lagos",
    name: "Alakoto",
    lcda: "Ajeromi Ifelodun",
    lat: 6.4571,
    long: 3.3295,
  },
  {
    state: "Lagos",
    name: "Araromi",
    lcda: "Ajeromi Ifelodun",
    lat: 6.454,
    long: 3.322,
  },
  {
    state: "Lagos",
    name: "Dankaka",
    lcda: "Ajeromi Ifelodun",
    lat: 6.4555,
    long: 3.3278,
  },
  {
    state: "Lagos",
    name: "Tolu",
    lcda: "Ajeromi Ifelodun",
    lat: 6.4588,
    long: 3.3156,
  },
  {
    state: "Lagos",
    name: "Awodi-Ora",
    lcda: "Ajeromi Ifelodun",
    lat: 6.4524,
    long: 3.3183,
  },
  {
    state: "Lagos",
    name: "Ibafon",
    lcda: "Ajeromi Ifelodun",
    lat: 6.4543,
    long: 3.3109,
  },
  {
    state: "Lagos",
    name: "Onibaba",
    lcda: "Ajeromi Ifelodun",
    lat: 6.4517,
    long: 3.3167,
  },
  {
    state: "Lagos",
    name: "Layeni",
    lcda: "Ajeromi Ifelodun",
    lat: 6.449,
    long: 3.3145,
  },
  {
    state: "Lagos",
    name: "Amukoko",
    lcda: "Ajeromi Ifelodun",
    lat: 6.4509,
    long: 3.3233,
  },
  {
    state: "Lagos",
    name: "Oridilu/Oke-Oja",
    lcda: "Ajeromi Ifelodun",
    lat: 6.4531,
    long: 3.3122,
  },
  {
    state: "Lagos",
    name: "Alaba Oro",
    lcda: "Ajeromi Ifelodun",
    lat: 6.4515,
    long: 3.3087,
  },
  {
    state: "Lagos",
    name: "Ayobo",
    lcda: "Alimosho",
    lat: 6.6033,
    long: 3.2489,
  },
  {
    state: "Lagos",
    name: "Ipaja",
    lcda: "Alimosho",
    lat: 6.6076,
    long: 3.2534,
  },
  {
    state: "Lagos",
    name: "Baruwa",
    lcda: "Alimosho",
    lat: 6.6165,
    long: 3.2661,
  },
  {
    state: "Lagos",
    name: "Command",
    lcda: "Alimosho",
    lat: 6.6142,
    long: 3.259,
  },
  {
    state: "Lagos",
    name: "Ijagemo",
    lcda: "Alimosho",
    lat: 6.5956,
    long: 3.2777,
  },
  {
    state: "Lagos",
    name: "Iyana-Ipaja",
    lcda: "Alimosho",
    lat: 6.6204,
    long: 3.2768,
  },
  {
    state: "Lagos",
    name: "Abesan",
    lcda: "Alimosho",
    lat: 6.6111,
    long: 3.2634,
  },
  {
    state: "Lagos",
    name: "Megida",
    lcda: "Alimosho",
    lat: 6.6107,
    long: 3.2568,
  },
  {
    state: "Lagos",
    name: "Ayetoro",
    lcda: "Alimosho",
    lat: 6.6012,
    long: 3.2417,
  },
  {
    state: "Lagos",
    name: "Opeki",
    lcda: "Alimosho",
    lat: 6.6029,
    long: 3.2495,
  },
  {
    state: "Lagos",
    name: "Olorunisola",
    lcda: "Alimosho",
    lat: 6.6073,
    long: 3.2456,
  },
  {
    state: "Lagos",
    name: "Mushin",
    lcda: "Alimosho",
    lat: 6.6149,
    long: 3.275,
  },
  {
    state: "Lagos",
    name: "Olowoira",
    lcda: "Alimosho",
    lat: 6.6221,
    long: 3.281,
  },
  {
    state: "Lagos",
    name: "Abule-Egba",
    lcda: "Agbado / Oke Odo",
    lat: 6.6413,
    long: 3.2822,
  },
  {
    state: "Lagos",
    name: "Alakuko",
    lcda: "Agbado / Oke Odo",
    lat: 6.6633,
    long: 3.2828,
  },
  {
    state: "Lagos",
    name: "Ajegunle",
    lcda: "Agbado / Oke Odo",
    lat: 6.662,
    long: 3.2924,
  },
  {
    state: "Lagos",
    name: "Alagbado",
    lcda: "Agbado / Oke Odo",
    lat: 6.6524,
    long: 3.285,
  },
  {
    state: "Lagos",
    name: "Ekoro",
    lcda: "Agbado / Oke Odo",
    lat: 6.6467,
    long: 3.28,
  },
  {
    state: "Lagos",
    name: "Meiran",
    lcda: "Agbado / Oke Odo",
    lat: 6.6501,
    long: 3.2908,
  },
  {
    state: "Lagos",
    name: "Kola",
    lcda: "Agbado / Oke Odo",
    lat: 6.6547,
    long: 3.3006,
  },
  {
    state: "Lagos",
    name: "Amikanle",
    lcda: "Agbado / Oke Odo",
    lat: 6.6589,
    long: 3.2775,
  },
  {
    state: "Lagos",
    name: "Jankara",
    lcda: "Agbado / Oke Odo",
    lat: 6.6462,
    long: 3.2888,
  },
  {
    state: "Lagos",
    name: "Ajasa Command",
    lcda: "Agbado / Oke Odo",
    lat: 6.6444,
    long: 3.2992,
  },
  {
    state: "Lagos",
    name: "Ijaiye",
    lcda: "Agbado / Oke Odo",
    lat: 6.6415,
    long: 3.2705,
  },
  {
    state: "Lagos",
    name: "Oko-Oba",
    lcda: "Agbado / Oke Odo",
    lat: 6.6521,
    long: 3.2855,
  },
  {
    state: "Lagos",
    name: "Egbe",
    lcda: "Egbe / Idimu",
    lat: 6.5896,
    long: 3.2713,
  },
  {
    state: "Lagos",
    name: "Idimu",
    lcda: "Egbe / Idimu",
    lat: 6.5994,
    long: 3.2671,
  },
  {
    state: "Lagos",
    name: "Ikotun",
    lcda: "Egbe / Idimu",
    lat: 6.5787,
    long: 3.2606,
  },
  {
    state: "Lagos",
    name: "Isheri-Olofin",
    lcda: "Egbe / Idimu",
    lat: 6.6039,
    long: 3.2551,
  },
  {
    state: "Lagos",
    name: "Council",
    lcda: "Egbe / Idimu",
    lat: 6.589,
    long: 3.2652,
  },
  {
    state: "Lagos",
    name: "Isheri-Idimu",
    lcda: "Egbe / Idimu",
    lat: 6.6052,
    long: 3.2635,
  },
  {
    state: "Lagos",
    name: "Liasu Road",
    lcda: "Egbe / Idimu",
    lat: 6.5967,
    long: 3.2708,
  },
  {
    state: "Lagos",
    name: "Arida",
    lcda: "Egbe / Idimu",
    lat: 6.5904,
    long: 3.2661,
  },
  {
    state: "Lagos",
    name: "Orelope",
    lcda: "Egbe / Idimu",
    lat: 6.5826,
    long: 3.2683,
  },
  {
    state: "Lagos",
    name: "Iyana Ejigbo",
    lcda: "Egbe / Idimu",
    lat: 6.5706,
    long: 3.2767,
  },
  {
    state: "Lagos",
    name: "Car Wash",
    lcda: "Egbe / Idimu",
    lat: 6.5845,
    long: 3.2741,
  },
  {
    state: "Lagos",
    name: "Pipeline",
    lcda: "Egbe / Idimu",
    lat: 6.5789,
    long: 3.2728,
  },
  {
    state: "Lagos",
    name: "Okerube",
    lcda: "Egbe / Idimu",
    lat: 6.6011,
    long: 3.2593,
  },
  {
    state: "Lagos",
    name: "Ikotun",
    lcda: "Ikotun Igando",
    lat: 6.5787,
    long: 3.2606,
  },
  {
    state: "Lagos",
    name: "Igando",
    lcda: "Ikotun Igando",
    lat: 6.5758,
    long: 3.2349,
  },
  {
    state: "Lagos",
    name: "Abaranje",
    lcda: "Ikotun Igando",
    lat: 6.5913,
    long: 3.2364,
  },
  {
    state: "Lagos",
    name: "Ijegun",
    lcda: "Ikotun Igando",
    lat: 6.5867,
    long: 3.2572,
  },
  {
    state: "Lagos",
    name: "Egan",
    lcda: "Ikotun Igando",
    lat: 6.6014,
    long: 3.2301,
  },
  {
    state: "Lagos",
    name: "Oko-Filling",
    lcda: "Ikotun Igando",
    lat: 6.5905,
    long: 3.2488,
  },
  {
    state: "Lagos",
    name: "Kirikiri",
    lcda: "Ikotun Igando",
    lat: 6.4626,
    long: 3.3416,
  },
  {
    state: "Lagos",
    name: "Okerube",
    lcda: "Ikotun Igando",
    lat: 6.6011,
    long: 3.2593,
  },
  {
    state: "Lagos",
    name: "Lanre",
    lcda: "Ikotun Igando",
    lat: 6.5918,
    long: 3.2457,
  },
  {
    state: "Lagos",
    name: "Iyana-Iba",
    lcda: "Ikotun Igando",
    lat: 6.4904,
    long: 3.2157,
  },
  {
    state: "Lagos",
    name: "Akesan",
    lcda: "Ikotun Igando",
    lat: 6.5909,
    long: 3.2226,
  },
  {
    state: "Lagos",
    name: "Obadore",
    lcda: "Ikotun Igando",
    lat: 6.5468,
    long: 3.1906,
  },
  {
    state: "Lagos",
    name: "Kudeibu",
    lcda: "Ikotun Igando",
    lat: 6.5842,
    long: 3.2505,
  },
  {
    state: "Lagos",
    name: "Lasu Road",
    lcda: "Ikotun Igando",
    lat: 6.5967,
    long: 3.2708,
  },
  {
    state: "Lagos",
    name: "Abesan Estate",
    lcda: "Mosan Okunola",
    lat: 6.6083,
    long: 3.2948,
  },
  {
    state: "Lagos",
    name: "Akowonjo",
    lcda: "Mosan Okunola",
    lat: 6.6104,
    long: 3.2923,
  },
  {
    state: "Lagos",
    name: "Gemade Estate",
    lcda: "Mosan Okunola",
    lat: 6.6109,
    long: 3.3068,
  },
  {
    state: "Lagos",
    name: "Gowon Estate",
    lcda: "Mosan Okunola",
    lat: 6.6137,
    long: 3.3145,
  },
  {
    state: "Lagos",
    name: "Shagari Estate",
    lcda: "Mosan Okunola",
    lat: 6.6174,
    long: 3.2991,
  },
  {
    state: "Lagos",
    name: "Abule-Odu",
    lcda: "Mosan Okunola",
    lat: 6.6087,
    long: 3.2819,
  },
  {
    state: "Lagos",
    name: "Olowo-Ira",
    lcda: "Mosan Okunola",
    lat: 6.6225,
    long: 3.2897,
  },
  {
    state: "Lagos",
    name: "Vanguard Estate",
    lcda: "Mosan Okunola",
    lat: 6.6156,
    long: 3.3081,
  },
  {
    state: "Lagos",
    name: "Pako",
    lcda: "Mosan Okunola",
    lat: 6.6172,
    long: 3.2857,
  },
  {
    state: "Lagos",
    name: "Abule-Egba",
    lcda: "Mosan Okunola",
    lat: 6.6483,
    long: 3.2869,
  },
  {
    state: "Lagos",
    name: "Gate Bus Stop",
    lcda: "Mosan Okunola",
    lat: 6.6117,
    long: 3.3001,
  },
  {
    state: "Lagos",
    name: "Bada",
    lcda: "Mosan Okunola",
    lat: 6.6235,
    long: 3.2794,
  },
  {
    state: "Lagos",
    name: "Fajol",
    lcda: "Mosan Okunola",
    lat: 6.6142,
    long: 3.2931,
  },
  {
    state: "Lagos",
    name: "Festac Town",
    lcda: "Amuwo Odofin",
    lat: 6.4892,
    long: 3.3343,
  },
  {
    state: "Lagos",
    name: "Amuwo",
    lcda: "Amuwo Odofin",
    lat: 6.4789,
    long: 3.3217,
  },
  {
    state: "Lagos",
    name: "Agboju",
    lcda: "Amuwo Odofin",
    lat: 6.4636,
    long: 3.3232,
  },
  {
    state: "Lagos",
    name: "Ijesha",
    lcda: "Amuwo Odofin",
    lat: 6.4891,
    long: 3.3249,
  },
  {
    state: "Lagos",
    name: "Maza Maza",
    lcda: "Amuwo Odofin",
    lat: 6.4691,
    long: 3.3172,
  },
  {
    state: "Lagos",
    name: "Mile 2",
    lcda: "Amuwo Odofin",
    lat: 6.4678,
    long: 3.3262,
  },
  {
    state: "Lagos",
    name: "Satellite Town",
    lcda: "Amuwo Odofin",
    lat: 6.4912,
    long: 3.3234,
  },
  {
    state: "Lagos",
    name: "Ojo Road",
    lcda: "Amuwo Odofin",
    lat: 6.473,
    long: 3.327,
  },
  {
    state: "Lagos",
    name: "Alakija",
    lcda: "Amuwo Odofin",
    lat: 6.4671,
    long: 3.3365,
  },
  {
    state: "Lagos",
    name: "1st Avenue",
    lcda: "Amuwo Odofin",
    lat: 6.4849,
    long: 3.3336,
  },
  {
    state: "Lagos",
    name: "2nd Avenue",
    lcda: "Amuwo Odofin",
    lat: 6.4843,
    long: 3.3312,
  },
  {
    state: "Lagos",
    name: "3rd Avenue",
    lcda: "Amuwo Odofin",
    lat: 6.4836,
    long: 3.3287,
  },
  {
    state: "Lagos",
    name: "Navy Town",
    lcda: "Amuwo Odofin",
    lat: 6.4877,
    long: 3.333,
  },
  {
    state: "Lagos",
    name: "Kirikiri",
    lcda: "Amuwo Odofin",
    lat: 6.485,
    long: 3.3099,
  },
  {
    state: "Lagos",
    name: "Ijegun Waterside",
    lcda: "Amuwo Odofin",
    lat: 6.4978,
    long: 3.3244,
  },
  {
    state: "Lagos",
    name: "Abule-Ado",
    lcda: "Amuwo Odofin",
    lat: 6.475,
    long: 3.307,
  },
  {
    state: "Lagos",
    name: "Finiger",
    lcda: "Amuwo Odofin",
    lat: 6.4855,
    long: 3.3352,
  },
  {
    state: "Lagos",
    name: "Iyano Oba",
    lcda: "Amuwo Odofin",
    lat: 6.4685,
    long: 3.329,
  },
  {
    state: "Lagos",
    name: "Oluti",
    lcda: "Amuwo Odofin",
    lat: 6.47,
    long: 3.3202,
  },
  {
    state: "Lagos",
    name: "Trade Fair Complex",
    lcda: "Amuwo Odofin",
    lat: 6.4565,
    long: 3.3255,
  },
  {
    state: "Lagos",
    name: "Volkswagen Estate",
    lcda: "Amuwo Odofin",
    lat: 6.4695,
    long: 3.3213,
  },
  {
    state: "Lagos",
    name: "Rockview Estate",
    lcda: "Amuwo Odofin",
    lat: 6.4847,
    long: 3.3381,
  },
  {
    state: "Lagos",
    name: "Apple Junction",
    lcda: "Amuwo Odofin",
    lat: 6.4713,
    long: 3.3276,
  },
  {
    state: "Lagos",
    name: "Apapa",
    lcda: "Apapa",
    lat: 6.4541,
    long: 3.3646,
  },
  {
    state: "Lagos",
    name: "Tincan Island",
    lcda: "Apapa",
    lat: 6.472,
    long: 3.3372,
  },
  {
    state: "Lagos",
    name: "Liverpool",
    lcda: "Apapa",
    lat: 6.4553,
    long: 3.3728,
  },
  {
    state: "Lagos",
    name: "Iganmu",
    lcda: "Apapa",
    lat: 6.4693,
    long: 3.3527,
  },
  {
    state: "Lagos",
    name: "Creek Road",
    lcda: "Apapa",
    lat: 6.4599,
    long: 3.3678,
  },
  {
    state: "Lagos",
    name: "Wharf Road",
    lcda: "Apapa",
    lat: 6.4662,
    long: 3.3559,
  },
  {
    state: "Lagos",
    name: "Point Road",
    lcda: "Apapa",
    lat: 6.4645,
    long: 3.3664,
  },
  {
    state: "Lagos",
    name: "Marine Beach",
    lcda: "Apapa",
    lat: 6.4548,
    long: 3.3581,
  },
  {
    state: "Lagos",
    name: "Ajegunle",
    lcda: "Apapa",
    lat: 6.482,
    long: 3.3075,
  },
  {
    state: "Lagos",
    name: "Ibru Jetty",
    lcda: "Apapa",
    lat: 6.4603,
    long: 3.3755,
  },
  {
    state: "Lagos",
    name: "Boundary",
    lcda: "Apapa",
    lat: 6.457,
    long: 3.3731,
  },
  {
    state: "Lagos",
    name: "Gaskiya",
    lcda: "Apapa",
    lat: 6.4707,
    long: 3.3194,
  },
  {
    state: "Lagos",
    name: "Ibafon",
    lcda: "Apapa",
    lat: 6.4665,
    long: 3.3544,
  },
  {
    state: "Lagos",
    name: "Olojowon",
    lcda: "Apapa",
    lat: 6.4652,
    long: 3.357,
  },
  {
    state: "Lagos",
    name: "Igborosun",
    lcda: "Badagry - Olorunda",
    lat: 6.0747,
    long: 3.0609,
  },
  {
    state: "Lagos",
    name: "Ibereko",
    lcda: "Badagry - Olorunda",
    lat: 6.0567,
    long: 3.0169,
  },
  {
    state: "Lagos",
    name: "Pota",
    lcda: "Badagry - Olorunda",
    lat: 6.0823,
    long: 3.0345,
  },
  {
    state: "Lagos",
    name: "Ilogbo Araromi",
    lcda: "Badagry - Olorunda",
    lat: 6.0781,
    long: 3.0563,
  },
  {
    state: "Lagos",
    name: "Iya Afin",
    lcda: "Badagry - Olorunda",
    lat: 6.0739,
    long: 3.0487,
  },
  {
    state: "Lagos",
    name: "Ajido",
    lcda: "Badagry - Olorunda",
    lat: 6.0865,
    long: 3.0179,
  },
  {
    state: "Lagos",
    name: "Gbethrome",
    lcda: "Badagry - Olorunda",
    lat: 6.0814,
    long: 3.0621,
  },
  {
    state: "Lagos",
    name: "Mowo",
    lcda: "Badagry - Olorunda",
    lat: 6.084,
    long: 3.0572,
  },
  {
    state: "Lagos",
    name: "Aradagun",
    lcda: "Badagry - Olorunda",
    lat: 6.0725,
    long: 3.0645,
  },
  {
    state: "Lagos",
    name: "Ijanikin",
    lcda: "Badagry - Olorunda",
    lat: 6.0423,
    long: 3.0417,
  },
  {
    state: "Lagos",
    name: "Kankon",
    lcda: "Badagry - Olorunda",
    lat: 6.0591,
    long: 3.0195,
  },
  {
    state: "Lagos",
    name: "Ikoga",
    lcda: "Badagry - Olorunda",
    lat: 6.0886,
    long: 3.0617,
  },
  {
    state: "Lagos",
    name: "Topo",
    lcda: "Badagry - Olorunda",
    lat: 6.0582,
    long: 3.0629,
  },
  {
    state: "Lagos",
    name: "Ilimi",
    lcda: "Badagry - Olorunda",
    lat: 6.0518,
    long: 3.0406,
  },
  {
    state: "Lagos",
    name: "Ajara",
    lcda: "Badagry - Olorunda",
    lat: 6.0775,
    long: 3.0392,
  },
  {
    state: "Lagos",
    name: "Ibereko Barracks",
    lcda: "Badagry - Olorunda",
    lat: 6.0634,
    long: 3.0223,
  },
  {
    state: "Lagos",
    name: "Badagry",
    lcda: "Badagry West",
    lat: 6.0573,
    long: 3.0582,
  },
  {
    state: "Lagos",
    name: "Seme",
    lcda: "Badagry West",
    lat: 6.0562,
    long: 3.0604,
  },
  {
    state: "Lagos",
    name: "Akarakiri",
    lcda: "Badagry West",
    lat: 6.0495,
    long: 3.0634,
  },
  {
    state: "Lagos",
    name: "Gbara",
    lcda: "Badagry West",
    lat: 6.0437,
    long: 3.0705,
  },
  {
    state: "Lagos",
    name: "Oguntona",
    lcda: "Badagry West",
    lat: 6.0361,
    long: 3.0758,
  },
  {
    state: "Lagos",
    name: "Idogbo",
    lcda: "Badagry West",
    lat: 6.0602,
    long: 3.0789,
  },
  {
    state: "Lagos",
    name: "Gbaji",
    lcda: "Badagry West",
    lat: 6.0484,
    long: 3.0697,
  },
  {
    state: "Lagos",
    name: "Oniwaya",
    lcda: "Badagry West",
    lat: 6.0452,
    long: 3.0724,
  },
  {
    state: "Lagos",
    name: "Mokoko",
    lcda: "Badagry West",
    lat: 6.0531,
    long: 3.0772,
  },
  {
    state: "Lagos",
    name: "Ikoga",
    lcda: "Badagry West",
    lat: 6.0584,
    long: 3.0676,
  },
  {
    state: "Lagos",
    name: "Ajara",
    lcda: "Badagry West",
    lat: 6.0621,
    long: 3.0609,
  },
  {
    state: "Lagos",
    name: "Topolo",
    lcda: "Badagry West",
    lat: 6.0545,
    long: 3.0651,
  },
  {
    state: "Lagos",
    name: "Gbagaun",
    lcda: "Badagry West",
    lat: 6.0498,
    long: 3.0742,
  },
  {
    state: "Lagos",
    name: "Ogu",
    lcda: "Badagry West",
    lat: 6.0536,
    long: 3.0794,
  },
  {
    state: "Lagos",
    name: "Akarabango",
    lcda: "Badagry West",
    lat: 6.0553,
    long: 3.0694,
  },
  {
    state: "Lagos",
    name: "Eredo",
    lcda: "Epe Eredo",
    lat: 6.5823,
    long: 3.9404,
  },
  {
    state: "Lagos",
    name: "Ijebu-Ode",
    lcda: "Epe Eredo",
    lat: 6.5752,
    long: 3.9481,
  },
  {
    state: "Lagos",
    name: "Imota",
    lcda: "Epe Eredo",
    lat: 6.5584,
    long: 3.962,
  },
  {
    state: "Lagos",
    name: "Ogundugbo",
    lcda: "Epe Eredo",
    lat: 6.5611,
    long: 3.9498,
  },
  {
    state: "Lagos",
    name: "Ibonwon",
    lcda: "Epe Eredo",
    lat: 6.5503,
    long: 3.9436,
  },
  {
    state: "Lagos",
    name: "Odo Noforija",
    lcda: "Epe Eredo",
    lat: 6.54,
    long: 3.9315,
  },
  {
    state: "Lagos",
    name: "Epe",
    lcda: "Epe Eredo",
    lat: 6.57,
    long: 3.9385,
  },
  {
    state: "Lagos",
    name: "Orofun",
    lcda: "Epe Eredo",
    lat: 6.5651,
    long: 3.9276,
  },
  {
    state: "Lagos",
    name: "Ilara",
    lcda: "Epe Eredo",
    lat: 6.5627,
    long: 3.9229,
  },
  {
    state: "Lagos",
    name: "Agbowa",
    lcda: "Epe Eredo",
    lat: 6.5715,
    long: 3.9232,
  },
  {
    state: "Lagos",
    name: "Ikosi",
    lcda: "Epe Eredo",
    lat: 6.5798,
    long: 3.9304,
  },
  {
    state: "Lagos",
    name: "Oke-Epe",
    lcda: "Epe Eredo",
    lat: 6.574,
    long: 3.9126,
  },
  {
    state: "Lagos",
    name: "Ajegunle",
    lcda: "Epe Eredo",
    lat: 6.5639,
    long: 3.9061,
  },
  {
    state: "Lagos",
    name: "Oke-Eri",
    lcda: "Epe Eredo",
    lat: 6.5618,
    long: 3.9144,
  },
  {
    state: "Lagos",
    name: "Itamaga",
    lcda: "Epe Eredo",
    lat: 6.5562,
    long: 3.9007,
  },
  {
    state: "Lagos",
    name: "Ikosi",
    lcda: "Epe Ikosi-Ejinrin",
    lat: 6.5825,
    long: 3.9877,
  },
  {
    state: "Lagos",
    name: "Ejinrin",
    lcda: "Epe Ikosi-Ejinrin",
    lat: 6.5768,
    long: 3.9712,
  },
  {
    state: "Lagos",
    name: "Oke Eri",
    lcda: "Epe Ikosi-Ejinrin",
    lat: 6.5676,
    long: 3.9849,
  },
  {
    state: "Lagos",
    name: "Olorunda",
    lcda: "Epe Ikosi-Ejinrin",
    lat: 6.561,
    long: 3.9793,
  },
  {
    state: "Lagos",
    name: "Odo-Noforija",
    lcda: "Epe Ikosi-Ejinrin",
    lat: 6.5582,
    long: 3.9674,
  },
  {
    state: "Lagos",
    name: "Igbokodo",
    lcda: "Epe Ikosi-Ejinrin",
    lat: 6.5517,
    long: 3.9568,
  },
  {
    state: "Lagos",
    name: "Agbowa",
    lcda: "Epe Ikosi-Ejinrin",
    lat: 6.5638,
    long: 3.9521,
  },
  {
    state: "Lagos",
    name: "Epe",
    lcda: "Epe Ikosi-Ejinrin",
    lat: 6.57,
    long: 3.9385,
  },
  {
    state: "Lagos",
    name: "Itamaga",
    lcda: "Epe Ikosi-Ejinrin",
    lat: 6.5594,
    long: 3.9243,
  },
  {
    state: "Lagos",
    name: "Odo-Olowo",
    lcda: "Epe Ikosi-Ejinrin",
    lat: 6.5501,
    long: 3.9329,
  },
  {
    state: "Lagos",
    name: "Ibeju",
    lcda: "Epe Ikosi-Ejinrin",
    lat: 6.5742,
    long: 3.9425,
  },
  {
    state: "Lagos",
    name: "Oju-Oluwa",
    lcda: "Epe Ikosi-Ejinrin",
    lat: 6.5618,
    long: 3.9218,
  },
  {
    state: "Lagos",
    name: "Idokun",
    lcda: "Epe Ikosi-Ejinrin",
    lat: 6.5663,
    long: 3.9332,
  },
  {
    state: "Lagos",
    name: "Ijebu-Ode",
    lcda: "Epe Ikosi-Ejinrin",
    lat: 6.5751,
    long: 3.952,
  },
  {
    state: "Lagos",
    name: "Aboshosh",
    lcda: "Epe Ikosi-Ejinrin",
    lat: 6.5803,
    long: 3.938,
  },
  {
    state: "Lagos",
    name: "Ewo",
    lcda: "Epe Ikosi-Ejinrin",
    lat: 6.578,
    long: 3.9253,
  },
  {
    state: "Lagos",
    name: "Aiyegbami",
    lcda: "Epe Ikosi-Ejinrin",
    lat: 6.5724,
    long: 3.9312,
  },
  {
    state: "Lagos",
    name: "Ikoyi",
    lcda: "Ikoyi Obalende",
    lat: 6.453,
    long: 3.4191,
  },
  {
    state: "Lagos",
    name: "Obalende",
    lcda: "Ikoyi Obalende",
    lat: 6.4532,
    long: 3.4165,
  },
  {
    state: "Lagos",
    name: "Bourdillon",
    lcda: "Ikoyi Obalende",
    lat: 6.4524,
    long: 3.4139,
  },
  {
    state: "Lagos",
    name: "Onikan",
    lcda: "Ikoyi Obalende",
    lat: 6.4518,
    long: 3.4197,
  },
  {
    state: "Lagos",
    name: "Awoyaya",
    lcda: "Ikoyi Obalende",
    lat: 6.4468,
    long: 3.4113,
  },
  {
    state: "Lagos",
    name: "Maroko",
    lcda: "Ikoyi Obalende",
    lat: 6.447,
    long: 3.4201,
  },
  {
    state: "Lagos",
    name: "Lagos Island",
    lcda: "Ikoyi Obalende",
    lat: 6.4462,
    long: 3.4175,
  },
  {
    state: "Lagos",
    name: "Coconut",
    lcda: "Ikoyi Obalende",
    lat: 6.4456,
    long: 3.4161,
  },
  {
    state: "Lagos",
    name: "Alagomeji",
    lcda: "Ikoyi Obalende",
    lat: 6.4448,
    long: 3.4148,
  },
  {
    state: "Lagos",
    name: "Eko Atlantic",
    lcda: "Ikoyi Obalende",
    lat: 6.4443,
    long: 3.4194,
  },
  {
    state: "Lagos",
    name: "Lagos Marina",
    lcda: "Ikoyi Obalende",
    lat: 6.4434,
    long: 3.4172,
  },
  {
    state: "Lagos",
    name: "Ikoyi-Lekki Link Bridge",
    lcda: "Ikoyi Obalende",
    lat: 6.4426,
    long: 3.4163,
  },
  {
    state: "Lagos",
    name: "Ologun Agbaje",
    lcda: "Ikoyi Obalende",
    lat: 6.4408,
    long: 3.419,
  },
  {
    state: "Lagos",
    name: "Victoria Island",
    lcda: "Iru / Victoria Island",
    lat: 6.4292,
    long: 3.4201,
  },
  {
    state: "Lagos",
    name: "Iru",
    lcda: "Iru / Victoria Island",
    lat: 6.4294,
    long: 3.4195,
  },
  {
    state: "Lagos",
    name: "Maroko",
    lcda: "Iru / Victoria Island",
    lat: 6.4295,
    long: 3.4192,
  },
  {
    state: "Lagos",
    name: "Lekki",
    lcda: "Iru / Victoria Island",
    lat: 6.4279,
    long: 3.4178,
  },
  {
    state: "Lagos",
    name: "Oniru",
    lcda: "Iru / Victoria Island",
    lat: 6.4268,
    long: 3.4169,
  },
  {
    state: "Lagos",
    name: "Tarkwa Bay",
    lcda: "Iru / Victoria Island",
    lat: 6.4265,
    long: 3.4182,
  },
  {
    state: "Lagos",
    name: "Tiamiyu Savage",
    lcda: "Iru / Victoria Island",
    lat: 6.4253,
    long: 3.417,
  },
  {
    state: "Lagos",
    name: "Bourdillon",
    lcda: "Iru / Victoria Island",
    lat: 6.4248,
    long: 3.4162,
  },
  {
    state: "Lagos",
    name: "Kofo Abayomi",
    lcda: "Iru / Victoria Island",
    lat: 6.4235,
    long: 3.4149,
  },
  {
    state: "Lagos",
    name: "Marina",
    lcda: "Iru / Victoria Island",
    lat: 6.4216,
    long: 3.4142,
  },
  {
    state: "Lagos",
    name: "Ahmadu Bello Way",
    lcda: "Iru / Victoria Island",
    lat: 6.4204,
    long: 3.413,
  },
  {
    state: "Lagos",
    name: "Alfred Rewane Road",
    lcda: "Iru / Victoria Island",
    lat: 6.4192,
    long: 3.4121,
  },
  {
    state: "Lagos",
    name: "Coconut Beach",
    lcda: "Iru / Victoria Island",
    lat: 6.4178,
    long: 3.4113,
  },
  {
    state: "Lagos",
    name: "Nigerian Ports Authority",
    lcda: "Iru / Victoria Island",
    lat: 6.4167,
    long: 3.4105,
  },
  {
    state: "Lagos",
    name: "Lekki",
    lcda: "Ibeju Lekki",
    lat: 6.4564,
    long: 3.5401,
  },
  {
    state: "Lagos",
    name: "Ajah",
    lcda: "Ibeju Lekki",
    lat: 6.4585,
    long: 3.5392,
  },
  {
    state: "Lagos",
    name: "Lekki Phase 1",
    lcda: "Ibeju Lekki",
    lat: 6.4442,
    long: 3.5405,
  },
  {
    state: "Lagos",
    name: "Lekki Phase 2",
    lcda: "Ibeju Lekki",
    lat: 6.4481,
    long: 3.5356,
  },
  {
    state: "Lagos",
    name: "Ibeju",
    lcda: "Ibeju Lekki",
    lat: 6.4548,
    long: 3.5189,
  },
  {
    state: "Lagos",
    name: "Epe",
    lcda: "Ibeju Lekki",
    lat: 6.5852,
    long: 3.7225,
  },
  {
    state: "Lagos",
    name: "Ikota",
    lcda: "Ibeju Lekki",
    lat: 6.4541,
    long: 3.5668,
  },
  {
    state: "Lagos",
    name: "Ikota Villa Estate",
    lcda: "Ibeju Lekki",
    lat: 6.4513,
    long: 3.5619,
  },
  {
    state: "Lagos",
    name: "Abijo",
    lcda: "Ibeju Lekki",
    lat: 6.4473,
    long: 3.551,
  },
  {
    state: "Lagos",
    name: "Eleko",
    lcda: "Ibeju Lekki",
    lat: 6.4312,
    long: 3.5555,
  },
  {
    state: "Lagos",
    name: "Elegushi",
    lcda: "Ibeju Lekki",
    lat: 6.4434,
    long: 3.5458,
  },
  {
    state: "Lagos",
    name: "Sangotedo",
    lcda: "Ibeju Lekki",
    lat: 6.4931,
    long: 3.577,
  },
  {
    state: "Lagos",
    name: "Lagos Business School",
    lcda: "Ibeju Lekki",
    lat: 6.4172,
    long: 3.5571,
  },
  {
    state: "Lagos",
    name: "VGC (Victoria Garden City)",
    lcda: "Ibeju Lekki",
    lat: 6.4633,
    long: 3.5399,
  },
  {
    state: "Lagos",
    name: "Atican Beach",
    lcda: "Ibeju Lekki",
    lat: 6.4586,
    long: 3.559,
  },
  {
    state: "Lagos",
    name: "Landmark Village",
    lcda: "Ibeju Lekki",
    lat: 6.46,
    long: 3.5542,
  },
  {
    state: "Lagos",
    name: "Shangotedo",
    lcda: "Ibeju Lekki",
    lat: 6.4744,
    long: 3.5454,
  },
  {
    state: "Lagos",
    name: "Lekki Free Trade Zone",
    lcda: "Ibeju Lekki",
    lat: 6.4618,
    long: 3.5887,
  },
  {
    state: "Lagos",
    name: "Ogunfowokan",
    lcda: "Ibeju Lekki",
    lat: 6.4472,
    long: 3.5365,
  },
  {
    state: "Lagos",
    name: "Eredo",
    lcda: "Ibeju Lekki",
    lat: 6.4635,
    long: 3.5486,
  },
  {
    state: "Lagos",
    name: "Oke Ibeju",
    lcda: "Ibeju Lekki",
    lat: 6.4778,
    long: 3.5222,
  },
  {
    state: "Lagos",
    name: "Funky Town",
    lcda: "Ibeju Lekki",
    lat: 6.4502,
    long: 3.53,
  },
  {
    state: "Lagos",
    name: "Coconut Beach",
    lcda: "Ibeju Lekki",
    lat: 6.4556,
    long: 3.5781,
  },
  {
    state: "Lagos",
    name: "Victoria Island Extension",
    lcda: "Ibeju Lekki",
    lat: 6.4296,
    long: 3.5505,
  },
  {
    state: "Lagos",
    name: "Epe Expressway",
    lcda: "Ibeju Lekki",
    lat: 6.5498,
    long: 3.7623,
  },
  {
    state: "Lagos",
    name: "Ogombo",
    lcda: "Ibeju Lekki",
    lat: 6.4729,
    long: 3.5369,
  },
  {
    state: "Lagos",
    name: "Ikate",
    lcda: "Ibeju Lekki",
    lat: 6.4332,
    long: 3.5433,
  },
  {
    state: "Lagos",
    name: "Ketu Epe",
    lcda: "Ibeju Lekki",
    lat: 6.5829,
    long: 3.7316,
  },
  {
    state: "Lagos",
    name: "Iru and Obeiro",
    lcda: "Ibeju Lekki",
    lat: 6.4565,
    long: 3.5325,
  },
  {
    state: "Lagos",
    name: "Ifako",
    lcda: "Ifako Ijaye",
    lat: 6.5873,
    long: 3.3495,
  },
  {
    state: "Lagos",
    name: "Ijaiye",
    lcda: "Ifako Ijaye",
    lat: 6.5906,
    long: 3.3421,
  },
  {
    state: "Lagos",
    name: "Oko-Oba",
    lcda: "Ifako Ijaye",
    lat: 6.5951,
    long: 3.3589,
  },
  {
    state: "Lagos",
    name: "Iju",
    lcda: "Ifako Ijaye",
    lat: 6.5972,
    long: 3.3754,
  },
  {
    state: "Lagos",
    name: "Abule Egba",
    lcda: "Ifako Ijaye",
    lat: 6.6081,
    long: 3.3355,
  },
  {
    state: "Lagos",
    name: "Iju-Ishaga",
    lcda: "Ifako Ijaye",
    lat: 6.6028,
    long: 3.3532,
  },
  {
    state: "Lagos",
    name: "Ikeja",
    lcda: "Ifako Ijaye",
    lat: 6.5248,
    long: 3.3495,
  },
  {
    state: "Lagos",
    name: "Ojodu",
    lcda: "Ifako Ijaye",
    lat: 6.5898,
    long: 3.356,
  },
  {
    state: "Lagos",
    name: "Omole",
    lcda: "Ifako Ijaye",
    lat: 6.5623,
    long: 3.3575,
  },
  {
    state: "Lagos",
    name: "Ogba",
    lcda: "Ifako Ijaye",
    lat: 6.5601,
    long: 3.3695,
  },
  {
    state: "Lagos",
    name: "Iyana Ipaja",
    lcda: "Ifako Ijaye",
    lat: 6.6062,
    long: 3.3477,
  },
  {
    state: "Lagos",
    name: "Ajao Estate",
    lcda: "Ifako Ijaye",
    lat: 6.5473,
    long: 3.3423,
  },
  {
    state: "Lagos",
    name: "Alagbado",
    lcda: "Ifako Ijaye",
    lat: 6.6179,
    long: 3.3668,
  },
  {
    state: "Lagos",
    name: "Ikeja",
    lcda: "Ikeja",
    lat: 6.5248,
    long: 3.3495,
  },
  {
    state: "Lagos",
    name: "GRA",
    lcda: "Ikeja",
    lat: 6.5241,
    long: 3.368,
  },
  {
    state: "Lagos",
    name: "Oregun",
    lcda: "Ikeja",
    lat: 6.5471,
    long: 3.3673,
  },
  {
    state: "Lagos",
    name: "Ogudu",
    lcda: "Ikeja",
    lat: 6.5672,
    long: 3.3895,
  },
  {
    state: "Lagos",
    name: "Onigbongbo",
    lcda: "Ikeja",
    lat: 6.5401,
    long: 3.3754,
  },
  {
    state: "Lagos",
    name: "Ojodu",
    lcda: "Ikeja",
    lat: 6.5898,
    long: 3.356,
  },
  {
    state: "Lagos",
    name: "Bodija",
    lcda: "Ikeja",
    lat: 6.5849,
    long: 3.3521,
  },
  {
    state: "Lagos",
    name: "Ikeja GRA",
    lcda: "Ikeja",
    lat: 6.521,
    long: 3.3597,
  },
  {
    state: "Lagos",
    name: "New Oko-Oba",
    lcda: "Ikeja",
    lat: 6.5998,
    long: 3.3419,
  },
  {
    state: "Lagos",
    name: "Baba Agba",
    lcda: "Ikeja",
    lat: 6.5651,
    long: 3.3599,
  },
  {
    state: "Lagos",
    name: "Shasha",
    lcda: "Ikeja",
    lat: 6.6012,
    long: 3.3476,
  },
  {
    state: "Lagos",
    name: "Abule-Oja",
    lcda: "Ikeja",
    lat: 6.5761,
    long: 3.3652,
  },
  {
    state: "Lagos",
    name: "Ketu",
    lcda: "Kosofe",
    lat: 6.5736,
    long: 3.3669,
  },
  {
    state: "Lagos",
    name: "Agboyi",
    lcda: "Kosofe",
    lat: 6.5901,
    long: 3.3581,
  },
  {
    state: "Lagos",
    name: "Ikosi",
    lcda: "Kosofe",
    lat: 6.5743,
    long: 3.3728,
  },
  {
    state: "Lagos",
    name: "Ojota",
    lcda: "Kosofe",
    lat: 6.562,
    long: 3.3683,
  },
  {
    state: "Lagos",
    name: "Olowoora",
    lcda: "Kosofe",
    lat: 6.5956,
    long: 3.3584,
  },
  {
    state: "Lagos",
    name: "Ibrahim Adesanya",
    lcda: "Kosofe",
    lat: 6.5677,
    long: 3.3571,
  },
  {
    state: "Lagos",
    name: "Isheri",
    lcda: "Kosofe",
    lat: 6.5748,
    long: 3.3543,
  },
  {
    state: "Lagos",
    name: "Ogudu",
    lcda: "Kosofe",
    lat: 6.5913,
    long: 3.3792,
  },
  {
    state: "Lagos",
    name: "Ikosi Ketu",
    lcda: "Kosofe",
    lat: 6.5823,
    long: 3.372,
  },
  {
    state: "Lagos",
    name: "Irawo",
    lcda: "Kosofe",
    lat: 6.5834,
    long: 3.3478,
  },
  {
    state: "Lagos",
    name: "Ketu Ikosi",
    lcda: "Kosofe",
    lat: 6.5782,
    long: 3.3597,
  },
  {
    state: "Lagos",
    name: "Ode",
    lcda: "Kosofe",
    lat: 6.5887,
    long: 3.3685,
  },
  {
    state: "Lagos",
    name: "Navy Town",
    lcda: "Kosofe",
    lat: 6.5884,
    long: 3.3841,
  },
  {
    state: "Lagos",
    name: "Yaba",
    lcda: "Lagos Mainland",
    lat: 6.5195,
    long: 3.3733,
  },
  {
    state: "Lagos",
    name: "Ebute Metta",
    lcda: "Lagos Mainland",
    lat: 6.5079,
    long: 3.3674,
  },
  {
    state: "Lagos",
    name: "Sabo",
    lcda: "Lagos Mainland",
    lat: 6.5144,
    long: 3.3672,
  },
  {
    state: "Lagos",
    name: "Oyingbo",
    lcda: "Lagos Mainland",
    lat: 6.4993,
    long: 3.3635,
  },
  {
    state: "Lagos",
    name: "Oshodi",
    lcda: "Lagos Mainland",
    lat: 6.5528,
    long: 3.3503,
  },
  {
    state: "Lagos",
    name: "Onigbongbo",
    lcda: "Lagos Mainland",
    lat: 6.5279,
    long: 3.3545,
  },
  {
    state: "Lagos",
    name: "Lagos Island",
    lcda: "Lagos Mainland",
    lat: 6.5089,
    long: 3.3436,
  },
  {
    state: "Lagos",
    name: "Aba",
    lcda: "Lagos Mainland",
    lat: 6.5273,
    long: 3.3675,
  },
  {
    state: "Lagos",
    name: "Mokola",
    lcda: "Lagos Mainland",
    lat: 6.5215,
    long: 3.368,
  },
  {
    state: "Lagos",
    name: "Fadeyi",
    lcda: "Lagos Mainland",
    lat: 6.5249,
    long: 3.3701,
  },
  {
    state: "Lagos",
    name: "Dahunsi",
    lcda: "Lagos Mainland",
    lat: 6.5232,
    long: 3.3712,
  },
  {
    state: "Lagos",
    name: "Adeleke",
    lcda: "Lagos Mainland",
    lat: 6.526,
    long: 3.3741,
  },
  {
    state: "Lagos",
    name: "Oko-Oba",
    lcda: "Lagos Mainland",
    lat: 6.5512,
    long: 3.3674,
  },
  {
    state: "Lagos",
    name: "Marina",
    lcda: "Lagos Island",
    lat: 6.4531,
    long: 3.3942,
  },
  {
    state: "Lagos",
    name: "CMS",
    lcda: "Lagos Island",
    lat: 6.4457,
    long: 3.4005,
  },
  {
    state: "Lagos",
    name: "Obalende",
    lcda: "Lagos Island",
    lat: 6.445,
    long: 3.3997,
  },
  {
    state: "Lagos",
    name: "Onikan",
    lcda: "Lagos Island",
    lat: 6.4538,
    long: 3.3982,
  },
  {
    state: "Lagos",
    name: "Ikoyi",
    lcda: "Lagos Island",
    lat: 6.4541,
    long: 3.4113,
  },
  {
    state: "Lagos",
    name: "Victoria Island",
    lcda: "Lagos Island",
    lat: 6.4271,
    long: 3.4208,
  },
  {
    state: "Lagos",
    name: "Apongbon",
    lcda: "Lagos Island",
    lat: 6.4533,
    long: 3.4003,
  },
  {
    state: "Lagos",
    name: "Tinubu Square",
    lcda: "Lagos Island",
    lat: 6.4485,
    long: 3.398,
  },
  {
    state: "Lagos",
    name: "Broad Street",
    lcda: "Lagos Island",
    lat: 6.4471,
    long: 3.3974,
  },
  {
    state: "Lagos",
    name: "Okepopo",
    lcda: "Lagos Island",
    lat: 6.4519,
    long: 3.3914,
  },
  {
    state: "Lagos",
    name: "Oke Arin",
    lcda: "Lagos Island",
    lat: 6.4488,
    long: 3.3961,
  },
  {
    state: "Lagos",
    name: "Oshodi",
    lcda: "Oshodi Isolo",
    lat: 6.5522,
    long: 3.3489,
  },
  {
    state: "Lagos",
    name: "Isolo",
    lcda: "Oshodi Isolo",
    lat: 6.5444,
    long: 3.3373,
  },
  {
    state: "Lagos",
    name: "Ajao Estate",
    lcda: "Oshodi Isolo",
    lat: 6.5457,
    long: 3.3408,
  },
  {
    state: "Lagos",
    name: "Ilasamaja",
    lcda: "Oshodi Isolo",
    lat: 6.5362,
    long: 3.3433,
  },
  {
    state: "Lagos",
    name: "Adebola",
    lcda: "Oshodi Isolo",
    lat: 6.5378,
    long: 3.3501,
  },
  {
    state: "Lagos",
    name: "Eguare",
    lcda: "Oshodi Isolo",
    lat: 6.5404,
    long: 3.3402,
  },
  {
    state: "Lagos",
    name: "Oshodi Expressway",
    lcda: "Oshodi Isolo",
    lat: 6.5493,
    long: 3.3471,
  },
  {
    state: "Lagos",
    name: "Kola",
    lcda: "Oshodi Isolo",
    lat: 6.5433,
    long: 3.3357,
  },
  {
    state: "Lagos",
    name: "Kirikiri",
    lcda: "Oshodi Isolo",
    lat: 6.4889,
    long: 3.3098,
  },
  {
    state: "Lagos",
    name: "Adeola",
    lcda: "Oshodi Isolo",
    lat: 6.547,
    long: 3.3484,
  },
  {
    state: "Lagos",
    name: "Aguda",
    lcda: "Surulere",
    lat: 6.5303,
    long: 3.3589,
  },
  {
    state: "Lagos",
    name: "Coker",
    lcda: "Surulere",
    lat: 6.5475,
    long: 3.3535,
  },
  {
    state: "Lagos",
    name: "Bode Thomas",
    lcda: "Surulere",
    lat: 6.5248,
    long: 3.3587,
  },
  {
    state: "Lagos",
    name: "Lawanson",
    lcda: "Surulere",
    lat: 6.5374,
    long: 3.36,
  },
  {
    state: "Lagos",
    name: "Oroolowu",
    lcda: "Surulere",
    lat: 6.5467,
    long: 3.3602,
  },
  {
    state: "Lagos",
    name: "Sangotedo",
    lcda: "Surulere",
    lat: 6.531,
    long: 3.3583,
  },
  {
    state: "Lagos",
    name: "Iponri",
    lcda: "Surulere",
    lat: 6.5273,
    long: 3.3582,
  },
  {
    state: "Lagos",
    name: "Adeniran Ogunsanya",
    lcda: "Surulere",
    lat: 6.5255,
    long: 3.3584,
  },
  {
    state: "Lagos",
    name: "Surulere",
    lcda: "Surulere",
    lat: 6.5247,
    long: 3.3585,
  },
  {
    state: "Lagos",
    name: "Ijesha",
    lcda: "Surulere",
    lat: 6.5258,
    long: 3.3587,
  },
  {
    state: "Lagos",
    name: "Mushin",
    lcda: "Surulere",
    lat: 6.535,
    long: 3.362,
  },
];
