/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as appRegionsIndexImport } from './routes/(app)/regions/index'
import { Route as appProfileIndexImport } from './routes/(app)/profile/index'
import { Route as appOrdersIndexImport } from './routes/(app)/orders/index'
import { Route as appOrdersOrderIdImport } from './routes/(app)/orders/$orderId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const appRegionsIndexRoute = appRegionsIndexImport.update({
  id: '/(app)/regions/',
  path: '/regions/',
  getParentRoute: () => rootRoute,
} as any)

const appProfileIndexRoute = appProfileIndexImport.update({
  id: '/(app)/profile/',
  path: '/profile/',
  getParentRoute: () => rootRoute,
} as any)

const appOrdersIndexRoute = appOrdersIndexImport.update({
  id: '/(app)/orders/',
  path: '/orders/',
  getParentRoute: () => rootRoute,
} as any)

const appOrdersOrderIdRoute = appOrdersOrderIdImport.update({
  id: '/(app)/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(app)/orders/$orderId': {
      id: '/(app)/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof appOrdersOrderIdImport
      parentRoute: typeof rootRoute
    }
    '/(app)/orders/': {
      id: '/(app)/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof appOrdersIndexImport
      parentRoute: typeof rootRoute
    }
    '/(app)/profile/': {
      id: '/(app)/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appProfileIndexImport
      parentRoute: typeof rootRoute
    }
    '/(app)/regions/': {
      id: '/(app)/regions/'
      path: '/regions'
      fullPath: '/regions'
      preLoaderRoute: typeof appRegionsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/orders/$orderId': typeof appOrdersOrderIdRoute
  '/orders': typeof appOrdersIndexRoute
  '/profile': typeof appProfileIndexRoute
  '/regions': typeof appRegionsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/orders/$orderId': typeof appOrdersOrderIdRoute
  '/orders': typeof appOrdersIndexRoute
  '/profile': typeof appProfileIndexRoute
  '/regions': typeof appRegionsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(app)/orders/$orderId': typeof appOrdersOrderIdRoute
  '/(app)/orders/': typeof appOrdersIndexRoute
  '/(app)/profile/': typeof appProfileIndexRoute
  '/(app)/regions/': typeof appRegionsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/orders/$orderId' | '/orders' | '/profile' | '/regions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/orders/$orderId' | '/orders' | '/profile' | '/regions'
  id:
    | '__root__'
    | '/'
    | '/(app)/orders/$orderId'
    | '/(app)/orders/'
    | '/(app)/profile/'
    | '/(app)/regions/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appOrdersOrderIdRoute: typeof appOrdersOrderIdRoute
  appOrdersIndexRoute: typeof appOrdersIndexRoute
  appProfileIndexRoute: typeof appProfileIndexRoute
  appRegionsIndexRoute: typeof appRegionsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appOrdersOrderIdRoute: appOrdersOrderIdRoute,
  appOrdersIndexRoute: appOrdersIndexRoute,
  appProfileIndexRoute: appProfileIndexRoute,
  appRegionsIndexRoute: appRegionsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(app)/orders/$orderId",
        "/(app)/orders/",
        "/(app)/profile/",
        "/(app)/regions/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(app)/orders/$orderId": {
      "filePath": "(app)/orders/$orderId.tsx"
    },
    "/(app)/orders/": {
      "filePath": "(app)/orders/index.tsx"
    },
    "/(app)/profile/": {
      "filePath": "(app)/profile/index.tsx"
    },
    "/(app)/regions/": {
      "filePath": "(app)/regions/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
